title: Stephen Parker | Data Analyst Portfolio
remote_theme: pages-themes/hacker@v0.2.0

baseurl: ""

email: <parkersteve2018@gmail.com>
description: >- # This shows up in search engine results and social shares
  Data Analyst specializing in SQL, Python, and Business Intelligence. 
  Exploring data to find actionable insights.
baseurl: "" # The subpath of your site, e.g. /portfolio/

# Social Media Links
github_username:  legodwarf
linkedin_username: https://www.linkedin.com/in/stephen-parker-lv/

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
